version: "3"
services:
  mongodb:
    build: ../mongodb/
    environment:
      - MONGO_INITDB_DATABASE=toolsdb
    volumes:
      - /data/db/mongo:/data/db
    restart: always
  ssh-on-web:
    # image: victor2333/ssh-on-web:latest
    build: ../
    environment:
      - MONGODB_URL=mongodb://mongodb/toolsdb
      - NODE_ENV=production
    volumes:
      # - /data/ssh-on-web/config:/ssh-on-web/config
      - /data/ssh-on-web/ssl:/ssh-on-web/ssl
    depends_on:
      - mongodb
    ports:
      - "0.0.0.0:443:8080"
    restart: always
